CFLAGS=-Wall -Wextra -pedantic -g
CC=gcc

pointers: pointers.c
	$(CC) pointers.c -o pointers $(CFLAGS)

strings: strings.c
	$(CC) strings.c -o strings $(CFLAGS)

copyinput: funpointers.c
	$(CC) funpointers.c -o funpointers $(CFLAGS)
